//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Web.WSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gtja.quant.com", ConfigurationName="WSService.WSServiceSoap")]
    public interface WSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gtja.quant.com/CanAccessDashboard", ReplyAction="*")]
        int CanAccessDashboard();
        
        // CODEGEN: 命名空间 http://gtja.quant.com 的元素名称 commCondJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gtja.quant.com/callService", ReplyAction="*")]
        DashBoard.Web.WSService.callServiceResponse callService(DashBoard.Web.WSService.callServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class callServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="callService", Namespace="http://gtja.quant.com", Order=0)]
        public DashBoard.Web.WSService.callServiceRequestBody Body;
        
        public callServiceRequest() {
        }
        
        public callServiceRequest(DashBoard.Web.WSService.callServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gtja.quant.com")]
    public partial class callServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string commCondJson;
        
        public callServiceRequestBody() {
        }
        
        public callServiceRequestBody(string commCondJson) {
            this.commCondJson = commCondJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class callServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="callServiceResponse", Namespace="http://gtja.quant.com", Order=0)]
        public DashBoard.Web.WSService.callServiceResponseBody Body;
        
        public callServiceResponse() {
        }
        
        public callServiceResponse(DashBoard.Web.WSService.callServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gtja.quant.com")]
    public partial class callServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string callServiceResult;
        
        public callServiceResponseBody() {
        }
        
        public callServiceResponseBody(string callServiceResult) {
            this.callServiceResult = callServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSServiceSoapChannel : DashBoard.Web.WSService.WSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSServiceSoapClient : System.ServiceModel.ClientBase<DashBoard.Web.WSService.WSServiceSoap>, DashBoard.Web.WSService.WSServiceSoap {
        
        public WSServiceSoapClient() {
        }
        
        public WSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CanAccessDashboard() {
            return base.Channel.CanAccessDashboard();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DashBoard.Web.WSService.callServiceResponse DashBoard.Web.WSService.WSServiceSoap.callService(DashBoard.Web.WSService.callServiceRequest request) {
            return base.Channel.callService(request);
        }
        
        public string callService(string commCondJson) {
            DashBoard.Web.WSService.callServiceRequest inValue = new DashBoard.Web.WSService.callServiceRequest();
            inValue.Body = new DashBoard.Web.WSService.callServiceRequestBody();
            inValue.Body.commCondJson = commCondJson;
            DashBoard.Web.WSService.callServiceResponse retVal = ((DashBoard.Web.WSService.WSServiceSoap)(this)).callService(inValue);
            return retVal.Body.callServiceResult;
        }
    }
}
