//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Web.SignService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignService.SignServiceSoap")]
    public interface SignServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 token 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanAccessDashboard", ReplyAction="*")]
        DashBoard.Web.SignService.CanAccessDashboardResponse CanAccessDashboard(DashBoard.Web.SignService.CanAccessDashboardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanAccessDashboardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanAccessDashboard", Namespace="http://tempuri.org/", Order=0)]
        public DashBoard.Web.SignService.CanAccessDashboardRequestBody Body;
        
        public CanAccessDashboardRequest() {
        }
        
        public CanAccessDashboardRequest(DashBoard.Web.SignService.CanAccessDashboardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanAccessDashboardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public CanAccessDashboardRequestBody() {
        }
        
        public CanAccessDashboardRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanAccessDashboardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanAccessDashboardResponse", Namespace="http://tempuri.org/", Order=0)]
        public DashBoard.Web.SignService.CanAccessDashboardResponseBody Body;
        
        public CanAccessDashboardResponse() {
        }
        
        public CanAccessDashboardResponse(DashBoard.Web.SignService.CanAccessDashboardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanAccessDashboardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DashBoard.Web.SignService.ServiceResult CanAccessDashboardResult;
        
        public CanAccessDashboardResponseBody() {
        }
        
        public CanAccessDashboardResponseBody(DashBoard.Web.SignService.ServiceResult CanAccessDashboardResult) {
            this.CanAccessDashboardResult = CanAccessDashboardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignServiceSoapChannel : DashBoard.Web.SignService.SignServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignServiceSoapClient : System.ServiceModel.ClientBase<DashBoard.Web.SignService.SignServiceSoap>, DashBoard.Web.SignService.SignServiceSoap {
        
        public SignServiceSoapClient() {
        }
        
        public SignServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DashBoard.Web.SignService.CanAccessDashboardResponse DashBoard.Web.SignService.SignServiceSoap.CanAccessDashboard(DashBoard.Web.SignService.CanAccessDashboardRequest request) {
            return base.Channel.CanAccessDashboard(request);
        }
        
        public DashBoard.Web.SignService.ServiceResult CanAccessDashboard(string token) {
            DashBoard.Web.SignService.CanAccessDashboardRequest inValue = new DashBoard.Web.SignService.CanAccessDashboardRequest();
            inValue.Body = new DashBoard.Web.SignService.CanAccessDashboardRequestBody();
            inValue.Body.token = token;
            DashBoard.Web.SignService.CanAccessDashboardResponse retVal = ((DashBoard.Web.SignService.SignServiceSoap)(this)).CanAccessDashboard(inValue);
            return retVal.Body.CanAccessDashboardResult;
        }
    }
}
