//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class custacctinfo
    {
        public int custid { get; set; }
        public string tradetype { get; set; }
        public string market { get; set; }
        public int fundid { get; set; }
        public string marketacc { get; set; }
        public string bankcode { get; set; }
        public string orgid { get; set; }
        public string trdpwd { get; set; }
        public string netaddr { get; set; }
        public string operway { get; set; }
        public string isdelete { get; set; }
        public int ownerid { get; set; }
    }
}
