//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalparam
    {
        public int generalparamid { get; set; }
        public int strategyno { get; set; }
        public string paramname { get; set; }
        public string paramtype { get; set; }
        public string paramvalue { get; set; }
        public string ispersonality { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> substrategyno { get; set; }
    }
}
