//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    
    public partial class GetCustomerTradeDetail
    {
        public int custid { get; set; }
        public int tradedate { get; set; }
        public string stkcode { get; set; }
        public int matchqty { get; set; }
        public decimal matchprice { get; set; }
        public string bsflag { get; set; }
    }
}
