//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class positionbasicinfotable
    {
        public int custid { get; set; }
        public decimal fundid { get; set; }
        public int sttradeno { get; set; }
        public int substrategyno { get; set; }
        public int strategyno { get; set; }
        public int stparamid { get; set; }
        public int createdate { get; set; }
        public int createtime { get; set; }
        public string bsflag { get; set; }
        public string currentstatus { get; set; }
        public decimal finishprocess { get; set; }
        public decimal openamount { get; set; }
        public decimal closeamount { get; set; }
        public decimal openavg { get; set; }
        public decimal floatincome { get; set; }
        public decimal incomerate { get; set; }
        public string isdelete { get; set; }
        public decimal positionvolume { get; set; }
        public string strategytype { get; set; }
        public Nullable<int> positiontype { get; set; }
        public Nullable<int> begintime { get; set; }
        public Nullable<int> endtime { get; set; }
        public Nullable<int> entrustfrequency { get; set; }
        public Nullable<int> reentrustfrequency { get; set; }
        public Nullable<int> entrusttimes { get; set; }
        public Nullable<int> canceltimes { get; set; }
        public Nullable<int> subordervalidperiod { get; set; }
        public string ordertype { get; set; }
        public Nullable<decimal> isorderqty { get; set; }
        public Nullable<decimal> orderqty { get; set; }
        public Nullable<decimal> isorderamount { get; set; }
        public Nullable<decimal> orderamount { get; set; }
        public Nullable<int> startmode { get; set; }
        public Nullable<int> executetime { get; set; }
        public string market { get; set; }
        public string operatetype { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> ordernum { get; set; }
        public Nullable<int> targetidentify { get; set; }
        public string orderpricetype { get; set; }
        public Nullable<int> orderpricelevel { get; set; }
        public Nullable<int> floatpoint { get; set; }
        public Nullable<int> orderlimitpricetype { get; set; }
        public Nullable<decimal> ordermaxprice { get; set; }
        public Nullable<decimal> orderminprice { get; set; }
        public Nullable<int> ordernumlimittype { get; set; }
        public Nullable<int> subordermaxqty { get; set; }
        public Nullable<decimal> orderlimitprice { get; set; }
        public Nullable<int> fixnum { get; set; }
        public Nullable<int> marketdeep { get; set; }
        public Nullable<decimal> markettraderatio { get; set; }
        public string fatherposition { get; set; }
        public Nullable<int> int1 { get; set; }
        public Nullable<int> int2 { get; set; }
        public Nullable<int> int3 { get; set; }
        public Nullable<int> int4 { get; set; }
        public Nullable<int> int5 { get; set; }
        public Nullable<int> int6 { get; set; }
        public Nullable<int> int7 { get; set; }
        public Nullable<int> int8 { get; set; }
        public Nullable<int> int9 { get; set; }
        public Nullable<int> int10 { get; set; }
        public Nullable<decimal> double1 { get; set; }
        public Nullable<decimal> double2 { get; set; }
        public Nullable<decimal> double3 { get; set; }
        public Nullable<decimal> double4 { get; set; }
        public Nullable<decimal> double5 { get; set; }
        public Nullable<decimal> double6 { get; set; }
        public Nullable<decimal> double7 { get; set; }
        public Nullable<decimal> double8 { get; set; }
        public Nullable<decimal> double9 { get; set; }
        public Nullable<decimal> double10 { get; set; }
        public string char1 { get; set; }
        public string char2 { get; set; }
        public string char3 { get; set; }
        public string char4 { get; set; }
        public string char5 { get; set; }
        public string char6 { get; set; }
        public string char7 { get; set; }
        public string char8 { get; set; }
        public string char9 { get; set; }
        public string char10 { get; set; }
        public string varchar1 { get; set; }
        public string varchar2 { get; set; }
        public string varchar3 { get; set; }
        public string varchar4 { get; set; }
        public string varchar5 { get; set; }
        public string varchar6 { get; set; }
        public string varchar7 { get; set; }
        public string varchar8 { get; set; }
        public string varchar9 { get; set; }
        public string varchar10 { get; set; }
        public Nullable<decimal> isorderqtyclose { get; set; }
        public Nullable<decimal> isorderamountclose { get; set; }
        public Nullable<decimal> orderqtyclose { get; set; }
        public Nullable<decimal> orderqtyadjustment { get; set; }
        public Nullable<decimal> isorderqtyadjustment { get; set; }
        public Nullable<decimal> orderamountclose { get; set; }
        public Nullable<decimal> orderamountadjustment { get; set; }
        public Nullable<decimal> isorderamountadjustment { get; set; }
        public Nullable<decimal> longfloatincome { get; set; }
        public Nullable<decimal> shortfloatincome { get; set; }
        public Nullable<int> positiondirect { get; set; }
        public decimal rongzicost { get; set; }
        public decimal rongquancost { get; set; }
        public decimal costprice { get; set; }
    }
}
