//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategyorder
    {
        public int custid { get; set; }
        public int ordersno { get; set; }
        public string tradetype { get; set; }
        public int orderdate { get; set; }
        public int strategyno { get; set; }
        public int substrategyno { get; set; }
        public int stparamid { get; set; }
        public int sttradeno { get; set; }
        public int opertime { get; set; }
        public string orderid { get; set; }
        public int fundid { get; set; }
        public string market { get; set; }
        public string marketacc { get; set; }
        public string orderstatus { get; set; }
        public string stkcode { get; set; }
        public string bsflag { get; set; }
        public decimal orderprice { get; set; }
        public int orderqty { get; set; }
        public string cancelflag { get; set; }
        public string remark { get; set; }
        public string creditdigestid { get; set; }
        public string credittype { get; set; }
        public Nullable<int> matchqty { get; set; }
        public Nullable<decimal> matchamt { get; set; }
        public string strategytype { get; set; }
    }
}
