//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategytrade
    {
        public int custid { get; set; }
        public int ordersno { get; set; }
        public int matchcode { get; set; }
        public string tradetype { get; set; }
        public int tradedate { get; set; }
        public string matchtype { get; set; }
        public int sttradeno { get; set; }
        public int tradetime { get; set; }
        public string market { get; set; }
        public string stkcode { get; set; }
        public int matchqty { get; set; }
        public decimal matchprice { get; set; }
        public decimal matchamt { get; set; }
        public int strategyno { get; set; }
        public int substrategyno { get; set; }
        public int stparamid { get; set; }
        public string secuid { get; set; }
        public string bsflag { get; set; }
        public string orderid { get; set; }
        public int orderqty { get; set; }
        public decimal orderprice { get; set; }
        public string creditdigestid { get; set; }
        public int fundid { get; set; }
    }
}
