//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategykind
    {
        public int kindid { get; set; }
        public string kindname { get; set; }
        public int fatherid { get; set; }
        public Nullable<int> templateid { get; set; }
        public string revs1 { get; set; }
        public string isdelete { get; set; }
        public int ownerid { get; set; }
    }
}
