//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class strategyinfo
    {
        public int strategyno { get; set; }
        public string strategyname { get; set; }
        public int kindid { get; set; }
        public string strategystatus { get; set; }
        public Nullable<decimal> forecast { get; set; }
        public string stratinfo { get; set; }
        public int templateid { get; set; }
        public Nullable<int> version { get; set; }
        public string iscalculate { get; set; }
        public string containername { get; set; }
        public string strategydir { get; set; }
        public string isoffline { get; set; }
        public string isalgostrategy { get; set; }
        public string isprivate { get; set; }
        public string isdelete { get; set; }
        public int ownerid { get; set; }
        public string seriesno { get; set; }
        public int accounttype { get; set; }
    }
}
